source "~/.config/tmux/_options.tmux"
source "~/.config/tmux/_plugins.tmux"
source "~/.config/tmux/_pomodoro.tmux"
source "~/.config/tmux/_catppuccin.tmux"
source "~/.config/tmux/_sessionx.tmux"

# Tmux Continuum
set -g @continuum-restore 'on'

# Tmux Resurrect
set -g @resurrect-processes 'ssh psql mysql sqlite3'
set -g @resurrect-strategy-nvim 'session'

run '$XDG_CACHE_HOME/tmux/plugins/tpm/tpm'
